theme: minima  # Change if you're using another theme
title: "Adam Oberman Math and AI professor website"
description: "My research and teaching"
nav:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research
  - title: "Teaching"
    url: /teaching
exclude:
  - _includes
  - _layouts
  - _site
  - node_modules
  - vendor
exclude:
  - 23_Math462
  - Lectures
  - Math462
  - Math562
  - old_files
  - pdfs
  - README.md
  - teaching2.md


