theme: minima  # Change if you're using another theme
title: "Adam Oberman Math and AI professor website"
description: "My research and teaching"
nav:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research
  - title: "Teaching"
    url: /teaching
include: [".htaccess"]
exclude: ["README.md", "Gemfile", "Gemfile.lock", "node_modules", "vendor"]
